name: Update GitHub Profile Stats

on:
  schedule:
    - cron: "0 */3 * * *"   
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@v3.32
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: usman22209
          filename: assets/github-metrics.svg

          base: header, activity, repositories

          plugin_languages: yes
          plugin_languages_indepth: no

          plugin_lines: yes
          plugin_followup: yes
          plugin_activity_limit: 5

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/github-metrics.svg
          git commit -m "Update metrics" || exit 0
          git push
